version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing NPM dependencies ...
      - npm install
  build:
    commands:
      - echo Creating new build ...
      - npm run build
