version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre-build:
    commands:
      - echo Installing NPM dependencies ...
      - npm install
  build:
    commands:
      - echo Starting servers ...
      - npm run dev